[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = ""
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/index.html"
healthcheckTimeout = 10
numReplicas = 1

[nginx]
staticDir = "/"
